### ISSUE TITLE
Localization Problem

### ISSUE THREAD

**Issue by gokdumano** [ncase/anxiety#17]
in **act4.md**, **line 925**, it says:

> b: Didn't Charles Manson win friends and influence people?

Did you guys localize it or keep it original? I don't think people in my country know who Charles Manson is, but we have some other similar figures. To deliver the message, I think localizing it would be better, what you say?

**Comment by lucasgcb** [comment]
The point isn't to call someone out, but inform the reader how someone who is terrible can still have friends and influence others; using a piece of history is just a way to do that.

From my experience, for that sort of thing, you may inject some redundancy to get the intentional message across, leaving the fact intact. 

> - "Didn't Charles Manson, who was a cult leader and serial killer, win friends and influence people?"

Alternatively, if you really want to avoid foreign names

> - "Aren't serial killers throughout history often notorious for being able to win friends and influence people?"

If you are really confident, you may then attempt to swap a fact for another that your readers are more likely to already know of, in order to get the same effect. In my case, for instance, I felt comfortable replacing the [Rhode Island nightclub fire](https://en.wikipedia.org/wiki/The_Station_nightclub_fire) with the [Boate Kiss fire](https://en.wikipedia.org/wiki/Kiss_nightclub_fire) which not only was arguably worse but more fresh in the recent memory of my country.
