### ISSUE TITLE
Russian translation | Русский перевод

### ISSUE THREAD

**Issue by awniar** [ncase/anxiety#5]
Потихоньку-помаленьку перевожу игру на русский, буду бесконечна рада соавторам (со-переводчикам?)

**Comment by toby3d** [comment]
Как и с [предыдущими](https://github.com/NotDotTeam/remember) [проектами](https://github.com/NotDotTeam/crowds) [Ники](https://github.com/NotDotTeam/trust) стартовал перевод текущего эксперимента. [Предлагаем присоединиться](https://github.com/NotDotTeam/anxiety). :)

**Comment by toby3d** [comment]
Current status of translating:
- [x] Interface and common elements (credits, intermission, intro, promo...)
- [x] ACT 1
- [x] ACT 2
- [x] ACT 3
- [x] ACT 4
- [x] Images and sprites
- [ ] Polishing and fix typos

**Comment by evyasonov** [comment]
Hey
Current Russian translation is a pure shit. Really. First it seems like google translate, but then it breaks the original meaning a lot! The "fear of being a bad person" was translated as "fear of bad reputation" which is much different. And there's a lot of such gems.

I recommend to remove current Russian translation for a while and open another issues for fixing or re-translating.

I'm <strike>translating</strike> localizing mental health article, so soon you will have a good Russian version – it's ~75% complete. So maybe next I will also localize the game or will participate in the new localization.

In any way, introducing a QA option might help a lot.

@ncase let me know what you think

**Comment by toby3d** [comment]
> Hey Current Russian translation is a pure shit. Really. First it seems like google translate, but then it breaks the original meaning a lot! The "fear of being a bad person" was translated as "fear of bad reputation" which is much different. And there's a lot of such gems.

Yes, I don't deny that the quality of the translation may not be very high. This is partly because I'm not a professional translator. Partly because the translation is constrained by technical implementation: fonts, the amount of characters allowed in blocks, fixed size sprites and so on. But as far as I can tell from the feedback, the translation came out at least not as bad as you describe it. It would be great to fix what other people are already referring to (there are quite a few!) instead of doing something completely from scratch.

> I recommend to remove current Russian translation for a while and open another issues for fixing or re-translating.

You can always open an issue in the translation repository with a translation and point out errors, I will be happy to fix them. Despite the vendor change, I still mirror repositories and have the tools to support them. I created the @NotDotTeam group specifically to accumulate Russian-speaking users to translate @ncase experiments into Russian and not to tie the translations to my persona.

> I'm translating localizing mental health article, so soon you will have a good Russian version – it's ~75% complete. So maybe next I will also localize the game or will participate in the new localization.

I admire you for taking on the work on the subject of the game, even though it's been out for quite some time. It would be great if we could help each other now and in the future.
